services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "1"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
    ports:
      - "1433:1433"
